version: '3.7'

services:
  backend_test:
    container_name: BackendTest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4445:8080'
    volumes:
      - backend_test_logs:/code/logs

volumes:
  backend_test_logs:
