import enum


class ErrorMessages(str, enum.Enum):
    GET_ALGORITHM_ALGORITHM_NOT_EXISTS = "ALGORITHM_DOES_NOT_EXISTS"

    # perfect numbers
    THE_LIST_OF_NUMBERS_IS_EMPTY = 'THE_LIST_OF_NUMBERS_IS_EMPTY'
    THE_LIST_OF_NUMBERS_CONTAINS_NEGATIVE_VALUE = 'THE_LIST_OF_NUMBERS_CONTAINS_NEGATIVE_VALUE'

    # matrix sub
    THE_LENGTHS_OF_THE_MATRICES_DO_NOT_MATCH = 'THE_LENGTHS_OF_THE_MATRICES_DO_NOT_MATCH'
    INCORRECT_NUMBER_OF_MATRIX_COLUMNS = 'INCORRECT_NUMBER_OF_MATRIX_COLUMNS'
    NO_VALUE_ENTERED_IN_THE_MATRIX = 'NO_VALUE_ENTERED_IN_THE_MATRIX'

    # quadratic equation
    THE_COEFFICIENTS_MUST_BE_NUMBERS = 'THE_COEFFICIENTS_MUST_BE_NUMBERS'
    THE_COEFFICIENT_FOR_X2_CANNOT_BE_EQUAL_TO_0 = 'THE_COEFFICIENT_FOR_X2_CANNOT_BE_EQUAL_TO_0'

    # fuel consumption
    THE_PARAMETER_VALUE_IS_LESS_THAN_ZERO = 'THE_PARAMETER_VALUE_IS_LESS_THAN_ZERO'

    # simplex method
    THIS_TABLE_IS_ENDLESS = 'THIS_TABLE_IS_ENDLESS'
    THERE_IS_NO_SOLUTION = 'THERE_IS_NO_SOLUTION'
    INCORRECT_INPUT_DATA = 'INCORRECT_INPUT_DATA'
